### ISSUE TITLE
sage-doc-9999 fails to build with current sage-9999 (9.5.beta5)

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#658]
This is on Prefix and `9.5.beta5` is installed. I assume the same on Gentoo, but I haven't gotten that far yet.
```
>>> Compiling source in /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999 ...
make -j13 doc-html PYTHON=/storage/strogdon/gentoo-rap/usr/bin/python3.9
Traceback (most recent call last):
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 62, in <module>
    from .build_options import (LANGUAGES, SPHINXOPTS, PAPER, OMIT,
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.9/site-packages/sage_docbuild/build_options.py", line 38, in <module>
    from sage.interfaces.gap import set_gap_memory_pool_size
ImportError: cannot import name 'set_gap_memory_pool_size' from 'sage.interfaces.gap' (/storage/strogdon/gentoo-rap/usr/lib/python3.9/site-packages/sage/interfaces/gap.py)
make doc-inventory--
make[1]: Entering directory '/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999/src/doc'
/storage/strogdon/gentoo-rap/usr/bin/python3.9 -m sage_docbuild --no-pdf-links .o inventory
Traceback (most recent call last):
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 62, in <module>
    from .build_options import (LANGUAGES, SPHINXOPTS, PAPER, OMIT,
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.9/site-packages/sage_docbuild/build_options.py", line 38, in <module>
    from sage.interfaces.gap import set_gap_memory_pool_size
ImportError: cannot import name 'set_gap_memory_pool_size' from 'sage.interfaces.gap' (/storage/strogdon/gentoo-rap/usr/lib/python3.9/site-packages/sage/interfaces/gap.py)
make[1]: *** [Makefile:20: doc-inventory--.o] Error 1
make[1]: Leaving directory '/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999/src/doc'
make: *** [Makefile:31: doc-inventory-reference] Error 2
```

**Comment by kiwifb** [comment]
That machine is brand new, so that was the right location. But I had created the file in the overlay, pushed it on github but I hadn't synchronised the system copy. So the link I had created was pointing to nothing.

The set is good for doing stuff with sage*-9999 ebuilds. I don't think it will be that useful for actual releases, but I should document it properly.
