### ISSUE TITLE
sci-mathematics/sage-5.2-r1 fails to build with gcc-4.7.0

### ISSUE THREAD

**Issue by houseofsuns** [cschwan/sage-on-gentoo#158]
On my hardened ~amd64 machine with gcc-4.7.0 I see the following build failure for sage

<pre>
x86_64-pc-linux-gnu-g++ -pthread -O2 -pipe -march=native -ggdb -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/finite_rings/element_givaro.cpp -o build/temp.linux-x86_64-2.7/sage/rings/finite_rings/element_givaro.o
In file included from /usr/include/givaro/givpoly1factor.h:176:0,
                 from /usr/include/givaro/givgfq.h:23,
                 from sage/rings/finite_rings/element_givaro.cpp:279:
/usr/include/givaro/givpoly1proot.inl: In instantiation of ‘Poly1FactorDom<Domain, Tag, RandIter>::Rep& Poly1FactorDom<Domain, Tag, RandIter>::give_prim_root(Poly1FactorDom<Domain, Tag, RandIter>::Rep&, const Rep&) const [with Domain = GFqDom<int>; Tag = Dense; RandIter = GivRandom; Poly1FactorDom<Domain, Tag, RandIter>::Rep = givvector<int, std::allocator<int> >]’:
/usr/include/givaro/givgfq.inl:1052:3:   required from ‘GFqDom<TT>::GFqDom(GFqDom<TT>::UTT, GFqDom<TT>::UTT, const std::vector<typename Signed_Trait<TT>::unsigned_type>&) [with TT = int; GFqDom<TT>::UTT = unsigned int; typename Signed_Trait<TT>::unsigned_type = unsigned int]’
sage/rings/finite_rings/element_givaro.cpp:3721:84:   required from here
/usr/include/givaro/givpoly1proot.inl:294:15: error: ‘degree’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
/usr/include/givaro/givpoly1proot.inl:294:15: note: declarations in dependent base ‘Poly1Dom<GFqDom<int>, Dense>’ are not found by unqualified lookup
/usr/include/givaro/givpoly1proot.inl:294:15: note: use ‘this->degree’ instead
</pre>
