### ISSUE TITLE
ipython < 7 versions were removed from gentoo

### ISSUE THREAD

**Issue by ngg** [cschwan/sage-on-gentoo#575]
Currently there is no compatible ipython and sage versions in this overlay, I think sage should be patched to use ipython-7.

Here is a patch from Arch Linux for this: https://aur.archlinux.org/cgit/aur.git/tree/sagemath-ipython7.patch?h=sagemath-git
(it's a really long patch, but most of it is only doctest fixes)

**Comment by kiwifb** [comment]
Darn. I was hoping they would stay in a bit longer. I know about the arch patch (and I know Antonio Rojas who work on sage-on-arch).

**Comment by kiwifb** [comment]
I was afraid of that. The main tree has ipython-7.5.0 but the latest arch patch is for 7.10. And yes there is an impact https://trac.sagemath.org/ticket/28197

**Comment by kiwifb** [comment]
I digged the previous patch from arch that is good for ipython-7.5. Testing things right now. There will be something in the overlay soon.

**Comment by strogdon** [comment]
It's probably known but with `ipython-7.10.0` I'm unable to build the docs
```
ImportError: cannot import name '_baseclass_reprs' from 'IPython.lib.pretty' (/storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/IPython/lib/pretty.py)
```
This probably one of many problems.

**Comment by kiwifb** [comment]
I have stuff in the vbraun branch that I should merge now. Works with ipython-7.5. There is just some specific doctests that fail that shouldn't. See trac above. I'll merge shortly.

**Comment by kiwifb** [comment]
Merged, so you can try stuff now. I haven't tested ipython-7.10 but it should build.

**Comment by strogdon** [comment]
Builds here with `ipython-7.10.0`.

**Comment by ngg** [comment]
Thanks for the quick fix! For me it works with ipython 7.5.0 (installed from gentoo) and also with ipython 7.13.0 (installed with pip)

**Comment by strogdon** [comment]
Probably not unexpected, but I have a HUGE number of doctest failures.

**Comment by kiwifb** [comment]
Yes, with ipython-7.10+ all doctests involving a dictionary will fail, or almost. See quoted sage ticket.
