### ISSUE TITLE
sage-5.2-r2 failed to build with gcc-4.7.1

### ISSUE THREAD

**Issue by zasdfgbnm** [cschwan/sage-on-gentoo#162]
<pre>
x86_64-pc-linux-gnu-g++ -pthread -Os -pipe -march=native -mtune=native -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/number_field/number_field_element_quadratic.cpp -o build/temp.linux-x86_64-2.7/sage/rings/number_field/number_field_element_quadratic.o
In file included from /usr/include/givaro/givpoly1factor.h:176:0,
                 from /usr/include/givaro/givgfq.h:23,
                 from sage/rings/finite_rings/element_givaro.cpp:279:
/usr/include/givaro/givpoly1proot.inl: In instantiation of ‘Poly1FactorDom<Domain, Tag, RandIter>::Rep& Poly1FactorDom<Domain, Tag, RandIter>::give_prim_root(Poly1FactorDom<Domain, Tag, RandIter>::Rep&, const Rep&) const [with Domain = GFqDom<int>; Tag = Dense; RandIter = GivRandom; Poly1FactorDom<Domain, Tag, RandIter>::Rep = givvector<int, std::allocator<int> >]’:
/usr/include/givaro/givgfq.inl:1052:3:   required from ‘GFqDom<TT>::GFqDom(GFqDom<TT>::UTT, GFqDom<TT>::UTT, const std::vector<typename Signed_Trait<TT>::unsigned_type>&) [with TT = int; GFqDom<TT>::UTT = unsigned int; typename Signed_Trait<TT>::unsigned_type = unsigned int]’
sage/rings/finite_rings/element_givaro.cpp:3721:84:   required from here
/usr/include/givaro/givpoly1proot.inl:294:15: error: ‘degree’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
/usr/include/givaro/givpoly1proot.inl:294:15: note: declarations in dependent base ‘Poly1Dom<GFqDom<int>, Dense>’ are not found by unqualified lookup
/usr/include/givaro/givpoly1proot.inl:294:15: note: use ‘this->degree’ instead
/usr/include/givaro/givpoly1proot.inl:301:9: error: ‘init’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
/usr/include/givaro/givpoly1proot.inl:301:9: note: declarations in dependent base ‘Poly1Dom<GFqDom<int>, Dense>’ are not found by unqualified lookup
/usr/include/givaro/givpoly1proot.inl:301:9: note: use ‘this->init’ instead
/usr/include/givaro/givpoly1proot.inl:311:9: error: ‘init’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
/usr/include/givaro/givpoly1proot.inl:311:9: note: declarations in dependent base ‘Poly1Dom<GFqDom<int>, Dense>’ are not found by unqualified lookup
/usr/include/givaro/givpoly1proot.inl:311:9: note: use ‘this->init’ instead
x86_64-pc-linux-gnu-gcc -pthread -Os -pipe -march=native -mtune=native -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/number_field/number_field_morphisms.c -o build/temp.linux-x86_64-2.7/sage/rings/number_field/number_field_morphisms.o
x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -Os -pipe -march=native -mtune=native -fno-strict-aliasing build/temp.linux-x86_64-2.7/sage/rings/number_field/number_field_morphisms.o -L/usr//lib -L/usr/lib64 -lcsage -lstdc++ -lntl -lpari -lgmp -lpython2.7 -o build/lib.linux-x86_64-2.7/sage/rings/number_field/number_field_morphisms.so
x86_64-pc-linux-gnu-gcc -pthread -Os -pipe -march=native -mtune=native -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/number_field/totallyreal.c -o build/temp.linux-x86_64-2.7/sage/rings/number_field/totallyreal.o
x86_64-pc-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,--as-needed -Os -pipe -march=native -mtune=native -fno-strict-aliasing build/temp.linux-x86_64-2.7/sage/rings/finite_rings/element_ntl_gf2e.o -L/usr//lib -L/usr/lib64 -lcsage -lntl -lgmp -lstdc++ -lntl -lpari -lgmp -lpython2.7 -o build/lib.linux-x86_64-2.7/sage/rings/finite_rings/element_ntl_gf2e.so
x86_64-pc-linux-gnu-gcc -pthread -Os -pipe -march=native -mtune=native -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/number_field/totallyreal_data.c -o build/temp.linux-x86_64-2.7/sage/rings/number_field/totallyreal_data.o
x86_64-pc-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,--as-needed -Os -pipe -march=native -mtune=native -fno-strict-aliasing build/temp.linux-x86_64-2.7/sage/rings/number_field/number_field_element_quadratic.o -L/usr//lib -L/usr/lib64 -lcsage -lntl -lgmp -lstdc++ -lntl -lpari -lgmp -lpython2.7 -o build/lib.linux-x86_64-2.7/sage/rings/number_field/number_field_element_quadratic.so
x86_64-pc-linux-gnu-gcc -pthread -Os -pipe -march=native -mtune=native -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/padics/local_generic_element.c -o build/temp.linux-x86_64-2.7/sage/rings/padics/local_generic_element.o
x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -Os -pipe -march=native -mtune=native -fno-strict-aliasing build/temp.linux-x86_64-2.7/sage/rings/padics/local_generic_element.o -L/usr//lib -L/usr/lib64 -lcsage -lstdc++ -lntl -lpari -lgmp -lpython2.7 -o build/lib.linux-x86_64-2.7/sage/rings/padics/local_generic_element.so
x86_64-pc-linux-gnu-gcc -pthread -Os -pipe -march=native -mtune=native -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/padics/padic_base_coercion.c -o build/temp.linux-x86_64-2.7/sage/rings/padics/padic_base_coercion.o
In file included from sage/rings/padics/padic_base_coercion.c:285:0:
/usr/include/csage/gmp_globals.h:6:0: warning: "EXTERN" redefined [enabled by default]
In file included from sage/rings/padics/padic_base_coercion.c:282:0:
/usr/include/csage/ntl_wrap.h:34:0: note: this is the location of the previous definition
x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -Os -pipe -march=native -mtune=native -fno-strict-aliasing build/temp.linux-x86_64-2.7/sage/rings/number_field/totallyreal.o -L/usr//lib -L/usr/lib64 -lcsage -lpari -lgmp -lstdc++ -lntl -lpari -lgmp -lpython2.7 -o build/lib.linux-x86_64-2.7/sage/rings/number_field/totallyreal.so
x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -Os -pipe -march=native -mtune=native -fno-strict-aliasing build/temp.linux-x86_64-2.7/sage/rings/number_field/totallyreal_data.o -L/usr//lib -L/usr/lib64 -lcsage -lgmp -lstdc++ -lntl -lpari -lgmp -lpython2.7 -o build/lib.linux-x86_64-2.7/sage/rings/number_field/totallyreal_data.so
x86_64-pc-linux-gnu-gcc -pthread -Os -pipe -march=native -mtune=native -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/padics/padic_base_generic_element.c -o build/temp.linux-x86_64-2.7/sage/rings/padics/padic_base_generic_element.o
x86_64-pc-linux-gnu-gcc -pthread -Os -pipe -march=native -mtune=native -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/padics/padic_capped_absolute_element.c -o build/temp.linux-x86_64-2.7/sage/rings/padics/padic_capped_absolute_element.o
In file included from sage/rings/padics/padic_capped_absolute_element.c:285:0:
/usr/include/csage/gmp_globals.h:6:0: warning: "EXTERN" redefined [enabled by default]
In file included from sage/rings/padics/padic_capped_absolute_element.c:282:0:
/usr/include/csage/ntl_wrap.h:34:0: note: this is the location of the previous definition
x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -Os -pipe -march=native -mtune=native -fno-strict-aliasing build/temp.linux-x86_64-2.7/sage/rings/padics/padic_base_generic_element.o -L/usr//lib -L/usr/lib64 -lcsage -lgmp -lstdc++ -lntl -lpari -lgmp -lpython2.7 -o build/lib.linux-x86_64-2.7/sage/rings/padics/padic_base_generic_element.so
x86_64-pc-linux-gnu-gcc -pthread -Os -pipe -march=native -mtune=native -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/padics/padic_capped_relative_element.c -o build/temp.linux-x86_64-2.7/sage/rings/padics/padic_capped_relative_element.o
In file included from sage/rings/padics/padic_capped_relative_element.c:289:0:
/usr/include/csage/gmp_globals.h:6:0: warning: "EXTERN" redefined [enabled by default]
In file included from sage/rings/padics/padic_capped_relative_element.c:282:0:
/usr/include/csage/ntl_wrap.h:34:0: note: this is the location of the previous definition
sage/rings/padics/padic_capped_relative_element.c: In function ‘__pyx_f_4sage_5rings_6padics_29padic_capped_relative_element_26pAdicCappedRelativeElement__set_from_mpz_both’:
sage/rings/padics/padic_capped_relative_element.c:6458:221: warning: passing argument 2 of ‘__gmpz_cmp’ from incompatible pointer type [enabled by default]
In file included from sage/rings/padics/padic_capped_relative_element.c:280:0:
/usr/include/gmp.h:755:20: note: expected ‘mpz_srcptr’ but argument is of type ‘struct __mpz_struct (*)[1]’
sage/rings/padics/padic_capped_relative_element.c: In function ‘__pyx_f_4sage_5rings_6padics_29padic_capped_relative_element_26pAdicCappedRelativeElement__set_mpz_into’:
sage/rings/padics/padic_capped_relative_element.c:8148:218: warning: passing argument 3 of ‘__gmpz_mul’ from incompatible pointer type [enabled by default]
In file included from sage/rings/padics/padic_capped_relative_element.c:280:0:
/usr/include/gmp.h:988:21: note: expected ‘mpz_srcptr’ but argument is of type ‘struct __mpz_struct (*)[1]’
sage/rings/padics/padic_capped_relative_element.c: In function ‘__pyx_f_4sage_5rings_6padics_29padic_capped_relative_element_26pAdicCappedRelativeElement__set_mpq_into’:
sage/rings/padics/padic_capped_relative_element.c:8227:214: warning: passing argument 2 of ‘__gmpz_set’ from incompatible pointer type [enabled by default]
In file included from sage/rings/padics/padic_capped_relative_element.c:280:0:
/usr/include/gmp.h:1073:21: note: expected ‘mpz_srcptr’ but argument is of type ‘struct __mpz_struct (*)[1]’
sage/rings/padics/padic_capped_relative_element.c:8288:242: warning: passing argument 3 of ‘__gmpz_mul’ from incompatible pointer type [enabled by default]
In file included from sage/rings/padics/padic_capped_relative_element.c:280:0:
/usr/include/gmp.h:988:21: note: expected ‘mpz_srcptr’ but argument is of type ‘struct __mpz_struct (*)[1]’
x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -Os -pipe -march=native -mtune=native -fno-strict-aliasing build/temp.linux-x86_64-2.7/sage/rings/padics/padic_base_coercion.o -L/usr//lib -L/usr/lib64 -lcsage -lgmp -lstdc++ -lntl -lpari -lgmp -lpython2.7 -o build/lib.linux-x86_64-2.7/sage/rings/padics/padic_base_coercion.so
x86_64-pc-linux-gnu-g++ -pthread -Os -pipe -march=native -mtune=native -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/padics/padic_ext_element.cpp -o build/temp.linux-x86_64-2.7/sage/rings/padics/padic_ext_element.o
x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -Os -pipe -march=native -mtune=native -fno-strict-aliasing build/temp.linux-x86_64-2.7/sage/rings/finite_rings/integer_mod.o -L/usr//lib -L/usr/lib64 -lcsage -lgmp -lstdc++ -lntl -lpari -lgmp -lpython2.7 -o build/lib.linux-x86_64-2.7/sage/rings/finite_rings/integer_mod.so
error: command 'x86_64-pc-linux-gnu-g++' failed with exit status 1
x86_64-pc-linux-gnu-gcc -pthread -Os -pipe -march=native -mtune=native -fno-strict-aliasing -fPIC -I/usr//include -I/usr/include/csage -Isage/ext -I/usr/include/python2.7 -c sage/rings/padics/padic_fixed_mod_element.c -o build/temp.linux-x86_64-2.7/sage/rings/padics/padic_fixed_mod_element.o
 * ERROR: sci-mathematics/sage-5.2-r2 failed (compile phase):
 *   Building failed
 * 
 * Call stack:
In file included from sage/rings/padics/padic_fixed_mod_element.c:285:0:
/usr/include/csage/gmp_globals.h:6:0: warning: "EXTERN" redefined [enabled by default]
In file included from sage/rings/padics/padic_fixed_mod_element.c:282:0:
/usr/include/csage/ntl_wrap.h:34:0: note: this is the location of the previous definition
</pre>
