### ISSUE TITLE
=sci-mathematics/lcalc-1.23-r5 fails to build with gcc-4.9

### ISSUE THREAD

**Issue by houseofsuns** [cschwan/sage-on-gentoo#310]
On my hardened ~amd64 box with gcc-4.9 I see the following error:

<pre>
In file included from ../include/L.h:532:0,
                 from Lriemannsiegel.cc:24:
../include/Ldirichlet_series.h:46:43: error: redeclaration of ‘Complex L_function<ttype>::dirichlet_series(Complex, long long int)’ may not have default arguments [-fpermissive]
 dirichlet_series(Complex s, long long N=-1)
</pre>

which was not there before, so I assume, that it fails with gcc-4.9.
