### ISSUE TITLE
fpylll-0.5.2dev (vanilla sage) build error with gentoo sci-libs/fplll-5.4.0

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#617]
FWIW the subject `fpylll-0.5.2dev` from vanilla will not build with system `sci-libs/fplll-5.4.0`

```
  building 'fpylll.fplll.integer_matrix' extension
  creating build/temp.linux-x86_64-3.8/build/src/fpylll/fplll
  g++ -std=gnu++11 -O2 -g -fPIC -Isrc/fpylll/fplll -I/local/sage-git/sage/local/lib/python3.8/site-packages/cysignals -I/local/sage-git/sage/local/include -I/local/sage-git/sage/local/lib/python3.8/site-packages/numpy/core/include -I/local/sage-git/sage/local/include -I/usr/include/python3.8 -c build/src/fpylll/fplll/integer_matrix.cpp -o build/temp.linux-x86_64-3.8/build/src/fpylll/fplll/integer_matrix.o -std=c++11 -O2 -g
  build/src/fpylll/fplll/integer_matrix.cpp:706:10: fatal error: fplll/sieve/sieve_gauss.h: No such file or directory
    706 | #include "fplll/sieve/sieve_gauss.h"
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
```
The `sieve` folder is provided by `sci-libs/fplll-5.3.0`. I just hit this after a `fplll` upgrade. It broke some doctests in vanilla.

**Comment by kiwifb** [comment]
Yes, there need to be some version limits. Until recently that was uncertain.

**Comment by kiwifb** [comment]
Sync the overlay, fpyll-0.5.2 now depend only on fplll-5.3.x.

**Comment by strogdon** [comment]
I have `fpylll-0.5.3` installed. Should that be masked?

**Comment by kiwifb** [comment]
It is a bit hard to mask something that has left the overlay (in favor of 0.5.4). In theory fplll-5.4.0+fpylll-0.5.4 should work with sage 9.2 as well as 9999. But vanilla 9.2 does use fplll-5.3.x+fpylll-0.5.2. You have to get one of these combinations.

**Comment by strogdon** [comment]
I see. I'm behind. I didn't know there was a `fpylll` update. Sync before typing. Let me try things.

**Comment by strogdon** [comment]
s-o-g works fine with fplll-5.4.0+fpylll-0.5.4. However, `fpylll-0.5.2dev` is used to build vanilla `9.3.beta4` which needs `fplll-5.3.x`. So I have to mask `fpylll-0.5.4` to get a system `fplll` that can be used in building vanilla.

**Comment by kiwifb** [comment]
Oh, I see. I very seldom do those these days and I am not bothered by what is system and what is not unless that's what I am testing.

**Comment by strogdon** [comment]
FWIW, I have two vanilla failures
```
sage -t --long --random-seed=0 src/sage/numerical/mip.pyx  # 1 doctest failed
sage -t --long --random-seed=0 src/sage/misc/package.py  # 1 doctest failed
```
The first because s-o-g uses `glpk-5.0` and the second, I'm assuming, because of https://trac.sagemath.org/ticket/30940
```
sage -t --long --random-seed=0 src/sage/misc/package.py
**********************************************************************
File "src/sage/misc/package.py", line 427, in sage.misc.package.standard_packages
Failed example:
    installed[0], installed[-1]  # optional - build
Expected:
    ('alabaster', 'zn_poly')
Got:
    ('alabaster', 'zipp')
```
`zn_poly` does not appear in my list of installed packages because the system version is used.
