### ISSUE TITLE
sage-9999 (sage-9.8.beta5) fails with python3.11

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#725]
Should this work with `python3.11`? Here I see
```
error: Command "x86_64-pc-linux-gnu-gcc -Wsign-compare -DNDEBUG -march=native -O2 -pipe -fPIC -I./sage/data_structures -I./sage/cpython -I/usr/lib/python3.11/site-packages/cysignals -I/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src -I/usr/lib/python3.11/site-packages/numpy/core/include -I/usr/include/python3.11 -Ibuild/cythonized -I/usr/include/python3.11 -c build/cythonized/sage/quivers/paths.c -o build/temp.linux-x86_64-cpython-311/build/cythonized/sage/quivers/paths.o -fno-strict-aliasing -DCYTHON_CLINE_IN_TRACEBACK=1" 
```
and early on
```
In file included from build/cythonized/sage/quivers/paths.c:3379:
./sage/cpython/cython_metaclass.h: In function ‘Sage_PyType_Ready’:
./sage/cpython/cython_metaclass.h:69:20: error: lvalue required as left operand of assignment
   69 |         Py_TYPE(t) = metaclass;
      |   
```
Parallel build does not help locating the issue.

**Comment by strogdon** [comment]
I omitted the location. It should be
```
   69 |         Py_TYPE(t) = metaclass;
      |                    ^
```

**Comment by kiwifb** [comment]
I thought it would, but it was pull at the last minute. So no :(

**Comment by strogdon** [comment]
It looks like a lot of stuff was removed just prior to the 9.8.beta5 release.

**Comment by kiwifb** [comment]
I turned off support for py3.11 on master again

**Comment by strogdon** [comment]
I suspect this can be closed. I have no issue now when using `py3.11`.
