### ISSUE TITLE
dev-python/cvxopt-1.1.6[glpk] won't compile against sci-mathematics/glpk-4.50

### ISSUE THREAD

**Issue by gagern** [cschwan/sage-on-gentoo#232]
Re-emerging cvxopt with the glpk extension after an upgrade of glpk to 4.50 fails due to numerous undefined symbols.

```
building 'glpk' extension
x86_64-pc-linux-gnu-gcc -pthread -march=amdfam10 -O2 -ggdb -pipe -fPIC -I/usr/include/python2.7 -c src/C/glpk.c -o /var/tmp/portage/dev-python/cvxopt-1.1.6/work/cvxopt-1.1.6-python2_7/temp.linux-x86_64-2.7/src/C/glpk.o
src/C/glpk.c:46:25: error: ‘LPX_K_MSGLEV’ undeclared here (not in a function)
src/C/glpk.c:47:25: error: ‘LPX_K_SCALE’ undeclared here (not in a function)
src/C/glpk.c:48:25: error: ‘LPX_K_DUAL’ undeclared here (not in a function)
src/C/glpk.c:49:25: error: ‘LPX_K_PRICE’ undeclared here (not in a function)
src/C/glpk.c:50:25: error: ‘LPX_K_RELAX’ undeclared here (not in a function)
src/C/glpk.c:51:25: error: ‘LPX_K_TOLBND’ undeclared here (not in a function)
src/C/glpk.c:52:25: error: ‘LPX_K_TOLDJ’ undeclared here (not in a function)
src/C/glpk.c:53:25: error: ‘LPX_K_TOLPIV’ undeclared here (not in a function)
src/C/glpk.c:54:25: error: ‘LPX_K_ROUND’ undeclared here (not in a function)
src/C/glpk.c:55:25: error: ‘LPX_K_OBJLL’ undeclared here (not in a function)
src/C/glpk.c:56:25: error: ‘LPX_K_OBJUL’ undeclared here (not in a function)
src/C/glpk.c:57:25: error: ‘LPX_K_ITLIM’ undeclared here (not in a function)
src/C/glpk.c:58:25: error: ‘LPX_K_ITCNT’ undeclared here (not in a function)
src/C/glpk.c:59:25: error: ‘LPX_K_TMLIM’ undeclared here (not in a function)
src/C/glpk.c:60:25: error: ‘LPX_K_OUTFRQ’ undeclared here (not in a function)
src/C/glpk.c:61:25: error: ‘LPX_K_OUTDLY’ undeclared here (not in a function)
src/C/glpk.c:62:25: error: ‘LPX_K_BRANCH’ undeclared here (not in a function)
src/C/glpk.c:63:25: error: ‘LPX_K_BTRACK’ undeclared here (not in a function)
src/C/glpk.c:64:25: error: ‘LPX_K_TOLINT’ undeclared here (not in a function)
src/C/glpk.c:65:25: error: ‘LPX_K_TOLOBJ’ undeclared here (not in a function)
src/C/glpk.c:66:25: error: ‘LPX_K_MPSINFO’ undeclared here (not in a function)
src/C/glpk.c:67:25: error: ‘LPX_K_MPSOBJ’ undeclared here (not in a function)
src/C/glpk.c:68:25: error: ‘LPX_K_MPSORIG’ undeclared here (not in a function)
src/C/glpk.c:69:25: error: ‘LPX_K_MPSWIDE’ undeclared here (not in a function)
src/C/glpk.c:70:25: error: ‘LPX_K_MPSFREE’ undeclared here (not in a function)
src/C/glpk.c:71:25: error: ‘LPX_K_MPSSKIP’ undeclared here (not in a function)
src/C/glpk.c:72:25: error: ‘LPX_K_LPTORIG’ undeclared here (not in a function)
src/C/glpk.c:73:25: error: ‘LPX_K_PRESOL’ undeclared here (not in a function)
src/C/glpk.c: In function ‘simplex’:
src/C/glpk.c:130:5: error: unknown type name ‘LPX’
src/C/glpk.c:186:8: warning: assignment makes pointer from integer without a cast [enabled by default]
src/C/glpk.c:192:35: error: ‘LPX_FR’ undeclared (first use in this function)
src/C/glpk.c:192:35: note: each undeclared identifier is reported only once for each function it appears in
src/C/glpk.c:195:35: error: ‘LPX_UP’ undeclared (first use in this function)
src/C/glpk.c:197:37: error: ‘LPX_FX’ undeclared (first use in this function)
src/C/glpk.c:322:14: error: ‘LPX_E_OK’ undeclared (first use in this function)
src/C/glpk.c:360:14: error: ‘LPX_E_NOPFS’ undeclared (first use in this function)
src/C/glpk.c:370:14: error: ‘LPX_E_NODFS’ undeclared (first use in this function)
src/C/glpk.c: In function ‘integer’:
src/C/glpk.c:431:5: error: unknown type name ‘LPX’
src/C/glpk.c:493:8: warning: assignment makes pointer from integer without a cast [enabled by default]
src/C/glpk.c:499:35: error: ‘LPX_FR’ undeclared (first use in this function)
src/C/glpk.c:502:35: error: ‘LPX_UP’ undeclared (first use in this function)
src/C/glpk.c:504:37: error: ‘LPX_FX’ undeclared (first use in this function)
src/C/glpk.c:650:2: warning: passing argument 1 of ‘glp_set_col_kind’ from incompatible pointer type [enabled by default]
In file included from src/C/glpk.c:24:0:
/usr/include/glpk.h:511:6: note: expected ‘struct glp_prob *’ but argument is of type ‘int *’
src/C/glpk.c:681:2: warning: passing argument 1 of ‘glp_set_col_kind’ from incompatible pointer type [enabled by default]
In file included from src/C/glpk.c:24:0:
/usr/include/glpk.h:511:6: note: expected ‘struct glp_prob *’ but argument is of type ‘int *’
src/C/glpk.c:692:14: error: ‘LPX_E_OK’ undeclared (first use in this function)
src/C/glpk.c:714:14: error: ‘LPX_E_TMLIM’ undeclared (first use in this function)
src/C/glpk.c:737:14: error: ‘LPX_E_FAULT’ undeclared (first use in this function)
src/C/glpk.c:746:7: error: ‘LPX_E_NOPFS’ undeclared (first use in this function)
src/C/glpk.c:755:7: error: ‘LPX_E_NODFS’ undeclared (first use in this function)
src/C/glpk.c:765:14: error: ‘LPX_E_ITLIM’ undeclared (first use in this function)
src/C/glpk.c:775:7: error: ‘LPX_E_SING’ undeclared (first use in this function)
error: command 'x86_64-pc-linux-gnu-gcc' failed with exit status 1
```
