### ISSUE TITLE
dev-lang/python-2.7.14-r100 fails to build with sys-libs/glibc-2.26-r3 - Modules/nismodule.c:17:10: fatal error: rpc/rpc.h: No such file or directory

### ISSUE THREAD

**Issue by devurandom** [cschwan/sage-on-gentoo#495]
```
x86_64-pc-linux-gnu-gcc -pthread -fPIC -fno-strict-aliasing -pipe -O2 -march=bdver3 -fwrapv -DNDEBUG -I. -I/var/tmp/portage/dev-lang/python-2.7.14-r100/work/Python-2.7.14/Include -I/var/tmp/portage/dev-lang/python-2.7.14-r100/work/x86_64-pc-linux-gnu -c /var/tmp/portage/dev-lang/python-2.7.14-r100/work/Python-2.7.14/Modules/nismodule.c -o build/temp.linux-x86_64-2.7/var/tmp/portage/dev-lang/python-2.7.14-r100/work/Python-2.7.14/Modules/nismodule.o
/var/tmp/portage/dev-lang/python-2.7.14-r100/work/Python-2.7.14/Modules/nismodule.c:17:10: fatal error: rpc/rpc.h: No such file or directory
 #include <rpc/rpc.h>
          ^~~~~~~~~~~
compilation terminated.
```

See-Also: https://bugs.gentoo.org/381391

[build.log](https://github.com/cschwan/sage-on-gentoo/files/1565269/build.log)

**Comment by kiwifb** [comment]
I see, I need to synchronize with 2.7.14-r1 in the main tree. Thank you for signalling, I will import that ASAP.

**Comment by kiwifb** [comment]
closed by 15f36e1bdaf43cc5bfbc172c8ef742d85edf94c9
