### ISSUE TITLE
sci-mathematics/sage fails to build with gcc-4.9

### ISSUE THREAD

**Issue by houseofsuns** [cschwan/sage-on-gentoo#311]
On my hardened ~amd64 box I see the following error for sage-6.2. This does not happen with gcc-4.8.

In file included from /usr/include/Lfunction/L.h:532:0,
                 from sage/libs/lcalc/lcalc_sage.h:1,
                 from sage/libs/lcalc/lcalc_Lfunction.cpp:355:
/usr/include/Lfunction/Ldirichlet_series.h:46:43: error: redeclaration of ‘Complex L_function<ttype>::dirichlet_series(Complex, long long int)’ may not have default arguments [-fpermissive]
 dirichlet_series(Complex s, long long N=-1)
                                           ^
This seems to be a near duplicate of the issue with lcalc and gcc-4.9.
